name: flutter_example_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  provider: ^6.1.2
  go_router: ^14.6.3
  package_info_plus: ^8.1.3
  dio: ^5.7.0
  data_table_2: ^2.5.18
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
